In [2]:
import numpy as np
import pandas as pd

In [2]:
array1=np.arange(1,6)

In [3]:
array1

array([1, 2, 3, 4, 5])

In [4]:
array1+array1

array([ 2,  4,  6,  8, 10])

In [5]:
np.exp(array1)

array([  2.71828183,   7.3890561 ,  20.08553692,  54.59815003,
       148.4131591 ])

In [6]:
np.square(array1)

array([ 1,  4,  9, 16, 25], dtype=int32)

In [7]:
np.sqrt(array1)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798])

In [8]:
np.log(array1)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791])

In [9]:
np.max(array1)

5

In [10]:
np.min(array1)

1

In [11]:
np.argmax(array1)

4

In [12]:
np.argmin(array1)

0

In [13]:
np.var(array1)

2.0

In [14]:
np.std(array1)

1.4142135623730951

In [15]:
np.mean(array1)

3.0

In [16]:
np.sum(array1)

15

In [19]:
np.unique(array1)

array([1, 2, 3, 4, 5])

In [5]:
ard1=np.random.randn(4,6)
ard1

array([[-0.30051942,  0.08751411,  1.50245272, -0.74655439,  1.89147247,
         1.06924517],
       [-0.25484203, -0.8086398 ,  0.32178022, -0.60146068,  1.65687171,
        -0.07748412],
       [-0.95471587,  0.28191554, -0.30625214,  0.90563308,  1.70097987,
        -0.73788143],
       [-1.08991772,  0.2093096 ,  0.03428897, -0.61164661, -0.51281453,
        -0.40133311]])

In [6]:
np.round(ard1)

array([[-0.,  0.,  2., -1.,  2.,  1.],
       [-0., -1.,  0., -1.,  2., -0.],
       [-1.,  0., -0.,  1.,  2., -1.],
       [-1.,  0.,  0., -1., -1., -0.]])